version: '3'

services:
  master:
    image: cluster:2.0
    hostname: master
    container_name: master
    ports:
      - "9870:9870"   # HDFS Web UI
      - "8088:8088"   # YARN Web UI
      - "10000:10000" 
      - "10002:10002" # DataNode UI
      - "19888:19888" # JobHistoryServer UI
      - "19890:19890" 
      - "18080:18080" # spark history
      - "8080:8080"   # Spark Web UI
      - "8081:8081"   # Flink Web UI
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop_net
    depends_on:
      - worker1
      - worker2
      - worker3
      - worker4


  worker1:
    image: cluster:2.0
    hostname: worker1
    container_name: worker1
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    networks:
      - hadoop_net


  worker2:
    image: cluster:2.0
    hostname: worker2
    container_name: worker2
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    networks:
      - hadoop_net


  worker3:
    image: cluster:2.0
    hostname: worker3
    container_name: worker3
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    networks:
      - hadoop_net


  worker4:
    image: cluster:2.0
    hostname: worker4
    container_name: worker4
    volumes:
      - hadoop_datanode4:/hadoop/dfs/data
    networks:
      - hadoop_net


  mysql:
    image: mysql:8
    hostname: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hive
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hadoop_net

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_datanode4:
  mysql_data:

networks:
  hadoop_net:
    driver: bridge