version: '3'

services:
  test:
    image: hadoop-base:3.3.6
    hostname: test
    container_name: test
    environment:
      - HADOOP_HOME=/opt/hadoop
    command: ['hello']

  master:
    image: hadoop-base:3.3.6
    hostname: master
    container_name: master
    ports:
      - "9870:9870"   # HDFS Web UI
      - "8088:8088"   # YARN Web UI
      - "10002:10002" # DataNode UI
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./etc/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./etc/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./etc/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./etc/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./etc/hadoop/workers:/opt/hadoop/etc/hadoop/workers
    networks:
      - hadoop_net


  worker1:
    image: hadoop-base:3.3.6
    hostname: worker1
    container_name: worker1
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
      - ./etc/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./etc/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./etc/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./etc/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./etc/hadoop/workers:/opt/hadoop/etc/hadoop/workers
    networks:
      - hadoop_net
    depends_on:
      - master

  worker2:
    image: hadoop-base:3.3.6
    hostname: worker2
    container_name: worker2
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
      - ./etc/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./etc/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./etc/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./etc/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./etc/hadoop/workers:/opt/hadoop/etc/hadoop/workers
    networks:
      - hadoop_net
    depends_on:
      - master

  worker3:
    image: hadoop-base:3.3.6
    hostname: worker3
    container_name: worker3
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
      - ./etc/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./etc/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./etc/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./etc/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./etc/hadoop/workers:/opt/hadoop/etc/hadoop/workers
    networks:
      - hadoop_net
    depends_on:
      - master

  worker4:
    image: hadoop-base:3.3.6
    hostname: worker4
    container_name: worker4
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - hadoop_datanode4:/hadoop/dfs/data
      - ./etc/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./etc/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./etc/hadoop/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./etc/hadoop/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./etc/hadoop/workers:/opt/hadoop/etc/hadoop/workers
    networks:
      - hadoop_net
    depends_on:
      - master

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_datanode4:

networks:
  hadoop_net:
    driver: bridge