version: '3'

services:
  master:
    image: hive-base:3.1.3
    hostname: master
    container_name: master
    ports:
      - "9870:9870"   # HDFS Web UI
      - "8088:8088"   # YARN Web UI
      - "10002:10002" # DataNode UI
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop_net


  worker1:
    image: hive-base:3.1.3
    hostname: worker1
    container_name: worker1
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    networks:
      - hadoop_net
    depends_on:
      - master

  worker2:
    image: hive-base:3.1.3
    hostname: worker2
    container_name: worker2
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    networks:
      - hadoop_net
    depends_on:
      - master

  worker3:
    image: hive-base:3.1.3
    hostname: worker3
    container_name: worker3
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    networks:
      - hadoop_net
    depends_on:
      - master

  worker4:
    image: hive-base:3.1.3
    hostname: worker4
    container_name: worker4
    volumes:
      - hadoop_datanode4:/hadoop/dfs/data
    networks:
      - hadoop_net
    depends_on:
      - master

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_datanode4:

networks:
  hadoop_net:
    driver: bridge